=== nationalparkservice/fcds/FCDSSchemas/campsiteAccessibilitySchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Campground Accessibility",
  "description": "Note: This file is a WIP, certain things have not been implemented yet, for example validation on many of the fields and required attributes",
  "type": "object",
  "required": [],
  "properties": {
    "environmentSetting": {
      "type": "string",
      "description": "Campsite Environment Setting",
      "enum": [
        "desert",
        "lake",
        "river",
        "stream",
        "canyon",
        "mountains",
        "forest",
        "plains",
        "rock formations",
        "waterfalls",
        "shade"
      ]
    },
    "environmentSettingAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for environment setting",
      "maxLength": 768
    },
    "parkingAccessibility": {
      "type": "object",
      "description": "Accessible parking details",
      "properties": {
        "parkingType": {
          "type": "string",
          "enum": ["lot", "spur"]
        },
        "spacesCount": {
          "type": "integer",
          "minimum": 0
        },
        "parkingLength": {
          "type": "number"
        },
        "parkingWidth": {
          "type": "number"
        },
        "accessibilityParkingSign": {
          "type": "boolean"
        },
        "surfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        }
      }
    },
    "parkingAccessibilityAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for parking",
      "maxLength": 768
    },
    "tentPad": {
      "type": "object",
      "description": "Tent pad/platform accessibility details",
      "properties": {
        "obviousTentPad": {
          "type": "boolean"
        },
        "location": {
          "type": "string"
        },
        "platformHeight": {
          "type": "number",
          "minimum": 0
        },
        "platformWidth": {
          "type": "number",
          "minimum": 0
        },
        "platformLength": {
          "type": "number",
          "minimum": 0
        },
        "ORAR": {
          "type": "string",
          "enum": ["stairs", "ramp", "level"]
        },
        "surfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        },
        "ORARSurfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        },
        "grade": {
          "type": "number",
          "minimum": 0
        },
        "slope": {
          "type": "number",
          "minimum": 0
        },
        "distanceFromParking": {
          "type": "number",
          "minimum": 0
        },
        "distanceFromFireRing": {
          "type": "number",
          "minimum": 0
        },
        "distanceToBench": {
          "type": "number",
          "minimum": 0
        },
        "distanceToBearBox": {
          "type": "number",
          "minimum": 0
        },
        "obstacles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "height": {
                "type": "number",
                "minimum": 0
              },
              "obstacleType": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "tentPadAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for tent pads",
      "maxLength": 768
    },
    "waterHookup": {
      "type": "object",
      "description": "Water Hookup details",
      "properties": {
        "spoutHeight": {
          "type": "number"
        },
        "faucetType": {
          "type": "string",
          "enum": [
            "knob",
            "lever",
            "paddle",
            "pump",
            "push button",
            "spring loaded",
            "automatic"
          ]
        },
        "ORARRoute": {
          "type": "boolean"
        },
        "clearance": {
          "type": "number",
          "minimum": 0
        },
        "slope": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "waterAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for water",
      "maxLength": 768
    },
    "electricHookup": {
      "type": "object",
      "description": "Electric Hookup details ",
      "properties": {
        "height": {
          "type": "number",
          "minimum": 0
        },
        "connectionType": {
          "type": "string"
        },
        "amps": {
          "type": "integer"
        },
        "ORARRoute": {
          "type": "boolean"
        },
        "clearance": {
          "type": "number",
          "minimum": 0
        },
        "slope": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "electricHookupAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for electric hookup",
      "maxLength": 768
    },
    "sewerHookup": {
      "type": "object",
      "description": "Sewer Hookup details",
      "properties": {
        "height": {
          "type": "number",
          "minimum": 0
        },
        "connectionType": {
          "type": "string"
        },
        "ORARRoute": {
          "type": "boolean"
        },
        "clearance": {
          "type": "number",
          "minimum": 0
        },
        "slope": {
          "type": "number",
          "minimum": 0
        }
      }
    },
    "sewerHookupAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for sewer hookup",
      "maxLength": 768
    },
    "fireRing": {
      "type": "object",
      "description": "Fire Ring details",
      "properties": {
        "height": {
          "type": "number",
          "minimum": 0
        },
        "depth": {
          "type": "number",
          "minimum": 0
        },
        "grateWeight": {
          "type": "number",
          "minimum": 0
        },
        "anchored": {
          "type": "boolean"
        },
        "stable": {
          "type": "boolean"
        },
        "clearSpace": {
          "type": "object",
          "properties": {
            "front": {
              "type": "boolean"
            },
            "side": {
              "type": "boolean"
            }
          }
        },
        "surfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        },
        "ORARsurfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        },
        "ORAR": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string"
            },
            "width": {
              "type": "number",
              "minimum": 0
            },
            "distance": {
              "type": "number",
              "minimum": 0
            },
            "length": {
              "type": "number",
              "minimum": 0
            }
          }
        },
        "singleWall": {
          "type": "boolean"
        }
      }
    },
    "fireRingAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for fire ring",
      "maxLength": 768
    },
    "table": {
      "type": "object",
      "description": "Table accessibility details",
      "properties": {
        "ORAR": {
          "type": "boolean"
        },
        "ORARToFire": {
          "type": "boolean"
        },
        "grade": {
          "type": "number",
          "minimum": 0
        },
        "quantity": {
          "type": "integer"
        },
        "ORARToTentPad": {
          "type": "boolean"
        },
        "anchored": {
          "type": "boolean"
        },
        "stable": {
          "type": "boolean"
        },
        "clearSpace": {
          "type": "object",
          "properties": {
            "front": {
              "type": "number",
              "minimum": 0
            },
            "side": {
              "type": "number",
              "minimum": 0
            }
          },
          "location": {
            "type": "string"
          },
          "moveable": {
            "type": "boolean"
          },
          "height": {
            "type": "number",
            "minimum": 0
          },
          "length": {
            "type": "number",
            "minimum": 0
          },
          "ORARSlope": {
            "type": "number",
            "minimum": 0
          },
          "wheelchairSeating": {
            "type": "boolean"
          },
          "wheelchairSeatLocation": {
            "type": "string"
          },
          "benches": {
            "type": "boolean"
          },
          "material": {
            "type": "string",
            "enum": [
              "concrete",
              "log",
              "lumber",
              "steel",
              "plastic",
              "aluminum"
            ],
            "surfaceType": {
              "type": "string",
              "enum": [
                "asphalt",
                "compacted gravel",
                "loose gravel",
                "concrete",
                "grass",
                "lumber",
                "native dirt",
                "brick",
                "sand"
              ]
            }
          }
        }
      }
    },
    "tableAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for table",
      "maxLength": 768
    },
    "shelter": {
      "type": "object",
      "description": "Shelter/structure details",
      "properties": {
        "ORAR": {
          "type": "boolean"
        },
        "surfaceType": {
          "type": "string",
          "enum": [
            "asphalt",
            "compacted gravel",
            "loose gravel",
            "concrete",
            "grass",
            "lumber",
            "native dirt",
            "brick",
            "sand"
          ]
        },
        "enclosed": {
          "type": "boolean"
        },
        "length": {
          "type": "number",
          "minimum": 0
        },
        "width": {
          "type": "number",
          "minimum": 0
        },
        "height": {
          "type": "number",
          "minimum": 0
        },
        "grade": {
          "type": "number",
          "minimum": 0
        },
        "locationToParking": {
          "type": "string"
        },
        "locationToFire": {
          "type": "string"
        },
        "locationToTentPad": {
          "type": "string"
        },
        "obstacles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "shelterAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for shelter",
      "maxLength": 768
    },
    "benches": {
      "type": "array",
      "description": "bench details",
      "items": {
        "type": "object",
        "properties": {
          "benchCount": {
            "type": "integer"
          },
          "location": {
            "type": "string"
          },
          "compliesWithORARStandards": {
            "type": "boolean"
          },
          "distantBetweenBenches": {
            "type": "number"
          },
          "seatHeight": {
            "type": "number"
          },
          "backAndArmrest": {
            "type": "boolean"
          },
          "benchLength": {
            "type": "number"
          },
          "ground": {
            "type": "object",
            "properties": {
              "width": {
                "type": "number"
              },
              "surfaceType": {
                "type": "string",
                "enum": [
                  "asphalt",
                  "compacted gravel",
                  "loose gravel ",
                  "concrete",
                  "grass",
                  "lumber",
                  "native dirt",
                  "brick",
                  "sand"
                ]
              }
            }
          }
        }
      }
    },
    "benchesAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for benches",
      "maxLength": 768
    },
    "noiseAccessibility": {
      "type": "array",
      "description": "Noise details",
      "items": {
        "type": "object",
        "properties": {
          "distanceToRoads": {
            "type": "string"
          },
          "distanceToAirport": {
            "type": "string"
          },
          "generator": {
            "type": "object",
            "properties": {
              "allowed": {
                "type": "boolean"
              },
              "areaAllowed": {
                "type": "string"
              }
            }
          },
          "noiseMakers": {
            "type": "string"
          },
          "distanceToGroupSites": {
            "type": "number"
          },
          "distanceToCampsites": {
            "type": "number"
          }
        }
      }
    },
    "noiseAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for noise",
      "maxLength": 768
    },
    "lightingAccessibility": {
      "type": "array",
      "description": "Lighting details",
      "items": {
        "type": "object",
        "properties": {
          "fullLight": {
            "type": "boolean"
          },
          "partialLight": {
            "type": "boolean"
          },
          "streetLighting": {
            "type": "boolean"
          },
          "lightedWalkways": {
            "type": "boolean"
          }
        }
      }
    },
    "lightingAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for lighting",
      "maxLength": 768
    },

    "bearBoxAccessibility": {
      "type": "array",
      "description": "Bear box details",
      "items": {
        "type": "object",
        "properties": {
          "distanceFromParking": {
            "type": "number"
          },
          "surfaceType": {
            "type": "string",
            "enum": [
              "asphalt",
              "compacted gravel",
              "loose gravel",
              "concrete",
              "grass",
              "lumber",
              "native dirt",
              "brick",
              "sand"
            ]
          },
          "opening": {
            "type": "object",
            "properties": {
              "openingType": {
                "type": "string"
              },
              "directionOfLid": {
                "type": "string"
              }
            }
          },
          "interferesWithAmenities": {
            "type": "boolean"
          },
          "depth": {
            "type": "number"
          },
          "height": {
            "type": "number"
          },
          "communal": {
            "type": "boolean"
          },
          "pressureToOpenLid": {
            "type": "number"
          },
          "ORAR": {
            "type": "boolean"
          }
        }
      }
    },
    "bearBoxAdditionalInfo": {
      "type": "string",
      "description": "Additional Information for a bear box",
      "maxLength": 768
    },
    "additionalAttribute": {
      "type": "string",
      "description": "Any additonal attributes not listed",
      "maxLength": 768
    }
  }
}

=== nationalparkservice/fcds/mockData/Mock_campsiteAccessibilitySchema.json
{"tableAdditionalInfo":"laborum dolore do","sewerHookup":{"connectionType":"id irure","ORARRoute":false,"slope":54466543.420168415,"clearance":13299233.145490708,"height":65841627.20997997},"fireRingAdditionalInfo":"sint","bearBoxAccessibility":[{"communal":true,"pressureToOpenLid":-35596002.27756694,"ORAR":false,"distanceFromParking":10069888.148695499,"surfaceType":"brick","height":-66204207.465224974,"interferesWithAmenities":false,"opening":{"directionOfLid":"sed tempor pariatur dolore cupidatat","openingType":"exercitation proident commodo dolor"},"depth":14074184.729724899},{"distanceFromParking":40254470.23086578,"surfaceType":"native dirt","pressureToOpenLid":1088059.0038614124,"communal":false,"opening":{"openingType":"anim sit nulla","directionOfLid":"velit ullamco in ipsum adipisicing"},"height":-7422226.900836334,"interferesWithAmenities":true,"ORAR":false,"depth":-87789805.93171841},{"interferesWithAmenities":false,"ORAR":false,"surfaceType":"grass","opening":{"openingType":"anim id","directionOfLid":"fugiat quis"},"pressureToOpenLid":-18594207.859077767,"height":-51973576.131038524,"distanceFromParking":-27519511.287388682,"depth":-71972745.43544242,"communal":false}],"parkingAccessibilityAdditionalInfo":"fugiat laborum","noiseAccessibility":[{"distanceToRoads":"occaecat aute esse ut aliquip","distanceToCampsites":15856949.486778587,"generator":{"allowed":false,"areaAllowed":"anim do"},"noiseMakers":"aute in","distanceToAirport":"occaecat aliqua sint","distanceToGroupSites":-1326926.2571869344}],"shelterAdditionalInfo":"veniam Lorem quis","electricHookup":{"height":57078049.34341956,"amps":-1110000,"ORARRoute":false,"slope":8401278.350096764,"clearance":66868205.1561277,"connectionType":"ipsum aute"},"lightingAdditionalInfo":"dolo","electricHookupAdditionalInfo":"cupidatat","benches":[{"benchCount":6509837,"seatHeight":-44340311.52618107,"location":"Ut","benchLength":-57635302.854225844,"compliesWithORARStandards":false,"ground":{"width":15933234.501024082,"surfaceType":"concrete"},"backAndArmrest":false,"distantBetweenBenches":5683558.959283322},{"seatHeight":-43862135.57790275,"compliesWithORARStandards":true,"benchCount":-96773459,"location":"do ad","ground":{"surfaceType":"compacted gravel","width":59471991.533736914},"distantBetweenBenches":22021853.853084534,"backAndArmrest":false,"benchLength":60317523.268618524}],"tentPad":{"surfaceType":"sand","platformWidth":70821866.9915255,"ORARSurfaceType":"concrete","distanceToBench":88519740.76794413,"location":"culpa Lorem laboris adipisicing","grade":93130522.89609918,"slope":37147931.42492241,"obviousTentPad":true,"distanceFromParking":299273.1333931964,"distanceToBearBox":98808115.46203348,"ORAR":"level","distanceFromFireRing":35986464.554175176,"platformLength":40086280.352092184,"platformHeight":91534397.79420425,"obstacles":[{"height":9977515.117329583,"obstacleType":"dolore fugiat qui occaecat ut"},{"obstacleType":"eu pariatur minim sint","height":87724243.37718245},{"height":21903839.442369953,"obstacleType":"minim qui pariatur in laboris"}]},"sewerHookupAdditionalInfo":"sit enim eu commodo labore","noiseAdditionalInfo":"ut Lorem tempor mollit","additionalAttribute":"do Lorem des","fireRing":{"depth":14404919.223145751,"clearSpace":{"front":true,"side":false},"ORARsurfaceType":"grass","stable":false,"anchored":false,"grateWeight":50412246.02297401,"surfaceType":"compacted gravel","height":22184986.444006905,"ORAR":{"width":35296859.35243323,"location":"sed officia Ut","length":22329149.03884131,"distance":89749295.06439589},"singleWall":true},"lightingAccessibility":[{"lightedWalkways":true,"fullLight":false,"partialLight":true,"streetLighting":false},{"streetLighting":true,"fullLight":true,"partialLight":false,"lightedWalkways":false},{"streetLighting":false,"lightedWalkways":false,"fullLight":true,"partialLight":false}],"environmentSettingAdditionalInfo":"ipsum","table":{"stable":false,"quantity":-47692555,"clearSpace":{"front":46012687.08797477,"side":43276444.225562714},"ORAR":true,"grade":35129103.85735677,"anchored":true,"ORARToTentPad":false,"ORARToFire":true},"tentPadAdditionalInfo":"est voluptate quis nostrud","parkingAccessibility":{"surfaceType":"sand","parkingType":"spur","parkingLength":-81450100.79681247,"spacesCount":91094436,"accessibilityParkingSign":false,"parkingWidth":21467146.99777186},"environmentSetting":"rock formations","bearBoxAdditionalInfo":"ut pariatur officia","benchesAdditionalInfo":"labore laborum id in","waterHookup":{"slope":61475417.79175707,"faucetType":"knob","spoutHeight":26371.404131889343,"ORARRoute":false,"clearance":68069518.43254615},"shelter":{"width":19896774.570537735,"locationToFire":"Duis adipisicing non proident sunt","enclosed":false,"grade":7682344.017947052,"locationToParking":"aliqua","length":41155612.40538694,"locationToTentPad":"officia labore occaecat amet","ORAR":false,"height":58464518.74029484,"obstacles":["do et qui proident ipsum","nulla culpa","sunt in","fugiat consequat labore"],"surfaceType":"sand"},"waterAdditionalInfo":"minim fugiat exercitation labore adipisicing"}
